export const START_FETCHING = 'START_FETCHING'
export const STOP_FETCHING = 'STOP_FETCHING'

export const CONNECTION_FAILED = 'CONNECTION_FAILED'
export const CONNECTION_SUCCEEDED = 'CONNECTION_SUCCEEDED'

export const RECEIVE_JURISDICTION = 'RECEIVE_JURISDICTION'
